# Generated by Django 3.2.9 on 2021-12-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBundle',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('download_link', models.CharField(default='', max_length=256)),
                ('update_link', models.CharField(default='', max_length=256)),
                ('root_path', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(default='', max_length=256)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_db.databundle')),
            ],
        ),
    ]
